import { DM_Sans, Playfair_Display } from "next/font/google";
import StoreProvider from "@/appStore/StoreProvider";
import Loader from '../../components/Common/Loader/index';
import CustomSnackbar from '../../components/Common/Snackbar/index';
import "../globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: '--font-dm-sans'
});
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: '--font-playfair'
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${dmSans.className} ${dmSans.variable} ${playfairDisplay.variable}`}>
                <StoreProvider>
                    {children}
                    <Loader />
                    <CustomSnackbar />
                </StoreProvider>
            </body>
        </html>
    );
}
