export const goldOptions = [
    {
        id:1,
        name:'14KT',
        value:'14KT',
    },
    {
        id:2,
        name:'18KT',
        value:'18KT',
    },
    {
        id:3,
        name:'22KT',
        value:'22KT'
    },
    {
        id:4,
        name:'24KT',
        value:'24KT',
    }
]
export const colorOptions = [
    {
        id:1,
        name:'Gold',
        value:'gold'
    },
    {
        id:1,
        name:'Rose Gold',
        value:'rosegold'
    },
    {
        id:1,
        name:'White Gold',
        value:'whitegold'
    },
]
export const sizeOptions = [
    {
        id:1,
        name:'XS',
        value:'xs',
    },
    {
        id:1,
        name:'S',
        value:'s',
    },
    {
        id:1,
        name:'M',
        value:'m',
    },
    {
        id:1,
        name:'L',
        value:'l',
    },
]