import { Inter } from "next/font/google";
// import "./globals.css";
// import NavBar from '../components/Common/NavBar';
// import Footer from '../components/Common/Footer';
import Sidenav from '../../components/Dashboard/Sidenav';
import StoreProvider from "@/appStore/StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider>
                    <Sidenav>
                        {children}
                    </Sidenav>
                    </StoreProvider>
            </body>
        </html>
    );
}
