import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from '@/components/Common/NavBar';
import Footer from '@/components/Common/Footer';
import StoreProvider from "@/appStore/StoreProvider";
import Loader from "@/components/Common/Loader/DiamondLoader";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NavBar />{children}<Loader/><Footer />
        </StoreProvider></body>
    </html>
  );
}
